#!/usr/bin/env ruby
# Simple script to see what tags contain a specific commit.
# Convenient for seeing what release a particular feature/bugfix was released in.

def search_for_commit(commit)
  %x{git show #{commit}}
  if $? != 0
    $stderr.puts "#{commit} is not a valid commit"
    return
  end

  tags = %x{git tag}.split(/\n/)

  tags.each do | tag |
    log = %x{git log --pretty="format:%H" #{tag} 2>/dev/null}
    if log.match(commit)
      puts "commit #{commit} found in tag #{tag}"
    else
      puts "commit #{commit} NOT found in tag #{tag}" if $verbose
    end
  end
end

# Make sure we're inside a git repo. If git branch returns nothing on stdin,
# get the expletive out of Dodge.
unless %x{git branch}
  exit 1
end

if ARGV.any? { |v| v.match(/-h|--help/) }
  puts "Usage: $0 commit ..."
  exit 0
end

$verbose = ARGV.delete("-v")
ARGV.each { |v| search_for_commit(v) }
