#!/usr/bin/env ruby

def search_for_commit(commit)
  %x{git show #{commit}}
  if $? != 0
    $stderr.puts "#{commit} is not a valid commit"
    return
  end

  tags = %x{git tag}.split(/\n/)

  tags.each do | tag |
    log = %x{git log --pretty="format:%H" #{tag}}
    if log.match(commit)
      puts "commit #{commit} found in tag #{tag}"
    end
  end
end

unless %x{git branch}
  exit 1
end
  

ARGV.each { |v| search_for_commit(v) }
